fullnameOverride: service-deployer

replicaCount: 1

# updateStrategy: Recreate

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

# env:
#   KEY: value

# secretRef: secretNmae

hostNetwork: false

dailyRestart:
  enabled: false
  schedule: "0 5 * * *" # At 5:00 AM daily

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      # nodePort: 30000

ingress:
  host: service.csnguyen.de
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      kube-system-redirect-https@kubernetescrd
  path: /
  pathType: Prefix
  tlsSecret: csnguyen-tls

startupProbe:
#   httpGet:
#     path: /
#     port: 80

persistentVolume:
  # - name: config
  #   mountPath: /config
  #   subPath:

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

volumeMounts:
#   - name: dri
#     mountPath: /dev/dri

volumes:
#   - name: dri
#     hostPath:
#       path: /dev/dri
